# Generated by Django 2.0.4 on 2019-08-26 18:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0002_auto_20190823_2135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnreadReceipts',
            new_name='UnreadReceipt',
        ),
    ]
