# Generated by Django 2.0.4 on 2019-08-26 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import realtimechatserver.helper


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0003_auto_20190826_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_Old',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=realtimechatserver.helper.create_hash, max_length=32, unique=True)),
                ('date', models.IntegerField(default=realtimechatserver.helper.time_stamp)),
                ('text', models.CharField(max_length=1024)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_old', to='messaging.MessageThread')),
            ],
        ),
    ]
