# Generated by Django 2.1.5 on 2019-08-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_auto_20190826_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagethread',
            name='psk',
            field=models.CharField(default='lol', max_length=32),
        ),
    ]
