# Generated by Django 2.1.5 on 2019-08-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_auto_20190829_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagethread',
            name='is_direct',
            field=models.BooleanField(default=False),
        ),
    ]
