# Generated by Django 2.1.5 on 2019-08-27 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_auto_20190827_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
